### ISSUE TITLE
Invalid use of `new`

### ISSUE THREAD

**Issue by QasimWani** [ratemydininghalls/rmdh_backend#1]
https://github.com/ratemydininghalls/rmdh_backend/blob/b7362b3e40ae51bf4d595ef6828971939442e2cf/api/School.js#L16

I don't believe this is the right way to create objects in mongoDB. 
In the post request for school.js, you need to access the db instance and insert to specific collection (School) like:\`db.collection.insertOne()  //Inserts a single document in the collection.`
Also, make use of callbacks to parse errors.
Read more: https://docs.mongodb.com/manual/reference/method/db.collection.insertOne/

**Comment by pengutopia** [comment]
fixed!
